name: AdvancedReplay
version: ${project.version}
main: me.jumper251.replay.ReplaySystem
authors: [Jumper251, MrF1yn]
depend: [ProtocolLib]
load: STARTUP
loadbefore: [BedWars1058, SlimeWorldManager]
commands:
  replay:
    description: Main Replay command
    aliases: [rp]